version: 3

server: https://app.fossa.com

project:
  id: github.com/revotech-group/fga-language
  name: github.com/revotech-group/fga-language
  link: openfga.dev
  url: github.com/revotech-group/fga-language

paths:
  exclude:
    - ./NOTICE
    - ./NOTICE.txt
